version: 2.1

orbs:
    node: circleci/node@5.1.0

jobs:
    setup:
        docker:
            - image: circleci/node:18.16.1-browsers
        steps:
            - checkout
            - node/install:
                install-yarn: true
            - run: node --version
            - run: yarn --version

workflow:
    ci:
        - setup
    